name: Lint and Test

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.2.2
    - name: Install dependencies
      run: |
        poetry install
    - name: Analysing the code with pylint
      run: |
        poetry run pylint -v `find . -name '*.py'` --disable=C0116,C0114,C0115
    - name: Check format
      run: |
        poetry run black --check ./
    - name: Running tests
      run: |
        poetry run python -m unittest discover -s test/ -v
