name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint prettytable black
    - name: Analysing the code with pylint
      run: |
        pylint -v `find . -name '*.py'` --disable=C0116,C0114,C0115
    - name: Check format
      run: |
        black --check ./
    - name: Running tests
      run: |
        python -m unittest discover -s test/ -v
